<?php
/**
 * Project: event-hub.
 * @author Adryan Eka Vandra <adryanekavandra@gmail.com>
 *
 * Date: 2/13/2019
 * Time: 12:21 PM
 */

namespace organizer\controllers;


use yii\web\Controller;

class LaporanController extends Controller
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }

    public function actionIndex(){

    }
    public function actionSummary(){

    }
    public function actionDetail(){

    }

    public function actionFeedback(){}


}