<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'password_reset_token' => 'Token Password Reset',
    'auth_key' => 'Kunci Auth',
    'birth_date' => 'Tanggal Lahir',
    'cell_phone' => 'Nomor Telepon Genggam',
    'created_at' => 'Dibuat Tanggal',
    'email' => 'Email',
    'first_name' => 'Nama Depan',
    'gender' => 'Jenis Kelamin',
    'id' => 'ID',
    'is_deleted' => 'Apakah Dihapus?',
    'last_name' => 'Nama Belakang',
    'middle_name' => 'Nama Tengah',
    'password_hash' => 'Password',
    'prefix' => 'Prefiks',
    'profile_picture' => 'Foto Profil',
    'updated_at' => 'Diperbarui Tanggal',
    'username' => 'Username',
];
