<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Auth Key' => 'Auth Key',
    'Birth Date' => 'Birth Date',
    'Cell Phone' => 'Cell Phone',
    'Created At' => 'Created At',
    'Email' => 'Email',
    'First Name' => 'First Name',
    'Gender' => 'Gender',
    'ID' => 'ID',
    'Is Deleted' => 'Is Deleted?',
    'Last Name' => 'Last Name',
    'Middle Name' => 'Middle Name',
    'Password Hash' => 'Password',
    'Password Reset Token' => 'Password Reset Token',
    'Prefix' => 'Prefix',
    'Profile Picture' => 'Profile Picture',
    'Updated At' => 'Updated At',
    'Username' => 'Username',
    'Code' => '',
    'Name' => '',
    'Topic Name' => '',
    'Type Name' => '',

];
