<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'password_rest_token' => '',
    'password_reset_token' => '@@Password Reset Token@@',
    'auth_key' => 'Auth Key',
    'birth_date' => 'Birth Date',
    'cell_phone' => 'Cell Phone',
    'created_at' => 'Created At',
    'email' => 'Email',
    'first_name' => 'First Name',
    'gender' => 'Gender',
    'id' => 'ID',
    'is_deleted' => 'Is Deleted?',
    'last_name' => 'Last Name',
    'middle_name' => 'Middle Name',
    'password_hash' => 'Password',
    'prefix' => 'Prefix',
    'profile_picture' => 'Profile Picture',
    'updated_at' => 'Updated At',
    'username' => 'Username',
];
